apiVersion: v1
kind: Service
metadata:
  labels:
    app: myweatherservice
  name: myweatherservice-lb
spec:
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 80
  selector:
    app: myweatherservice
  type: LoadBalancer

